GossipProject2/config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get '/acceuil', to:'pages#index'
  resources :gossips
  root to:'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

GossipProject2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GossipProject2/app/models/contact.rb
class Contact < ApplicationRecord
end

GossipProject2/app/models/gossip.rb
class Gossip < ApplicationRecord
end

GossipProject2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

GossipProject2/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :tel, :email)
    end
end

GossipProject2/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: [:show, :edit, :update, :destroy]

  # GET /gossips
  # GET /gossips.json
  def index
    @gossips = Gossip.all
  end

  # GET /gossips/1
  # GET /gossips/1.json
  def show
  end

  # GET /gossips/new
  def new
    @gossip = Gossip.new
  end

  # GET /gossips/1/edit
  def edit
  end

  # POST /gossips
  # POST /gossips.json
  def create
    @gossip = Gossip.new(gossip_params)

    respond_to do |format|
      if @gossip.save
        format.html { redirect_to @gossip, notice: 'Gossip was successfully created.' }
        format.json { render :show, status: :created, location: @gossip }
      else
        format.html { render :new }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gossips/1
  # PATCH/PUT /gossips/1.json
  def update
    respond_to do |format|
      if @gossip.update(gossip_params)
        format.html { redirect_to @gossip, notice: 'Gossip was successfully updated.' }
        format.json { render :show, status: :ok, location: @gossip }
      else
        format.html { render :edit }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gossips/1
  # DELETE /gossips/1.json
  def destroy
    @gossip.destroy
    respond_to do |format|
      format.html { redirect_to gossips_url, notice: 'Gossip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gossip
      @gossip = Gossip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gossip_params
      params.require(:gossip).permit(:author, :content)
    end
end

GossipProject2/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
  end

  def home
  end
end

GossipProject2/app/helpers/application_helper.rb
module ApplicationHelper
end

GossipProject2/app/helpers/contacts_helper.rb
module ContactsHelper
end

GossipProject2/app/helpers/gossips_helper.rb
module GossipsHelper
end

GossipProject2/app/helpers/pages_helper.rb
module PagesHelper
end

GossipProject2/app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name ,class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name,class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.number_field :tel ,class:'form-control'%>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email,class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

GossipProject2/app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

GossipProject2/app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
  <h1>Contact</h1>
</div>

<%= link_to 'New Contact', new_contact_path ,class:'btn btn-success'%>

<div class="row">
  <% @contacts.each do |contact| %>
  <div class="col-4">
    <div class="card mt-3" style="width: 18rem;">
        <img src="./img/user.png" width=50>
      <div class="card-body">

        <h5 class="card-title"><%= contact.first_name %></h5>
        <h4> <%= contact.last_name %> </h4>
        <p class="card-text"> <%= contact.tel %> </p>
          <p class="card-text"> <%= contact.email %> </p>


          <%= link_to 'Show', contact, class: 'btn btn-primary' %>
          <%= link_to 'Edit', edit_contact_path(contact), class:'btn btn-warning' %>
          <%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

GossipProject2/app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

GossipProject2/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @contact.tel %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

GossipProject2/app/views/gossips/_form.html.erb
<%= form_with(model: gossip, local: true) do |form| %>
  <% if gossip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>

      <ul>
        <% gossip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">

      <div class="field">
        <%= form.label :author %>
        <%= form.text_field :author,class:'form-control' %>
      </div>

      <div class="field">
        <%= form.label :content %>
        <%= form.text_area :content,class:'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit%>
      </div>
  <% end %>
</div>

GossipProject2/app/views/gossips/edit.html.erb
<h1>Editing Gossip</h1>

<%= render 'form', gossip: @gossip %>

<%= link_to 'Show', @gossip %> |
<%= link_to 'Back', gossips_path %>

GossipProject2/app/views/gossips/index.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
    <h1>Gossips</h1>
</div>
<div class="text-center">
    <%= link_to 'New Gossip', new_gossip_path, class:'btn btn-success' %>
</div>





<div class="row">
<% @gossips.each do |gossip| %>
  <div class="col-4">
    <div class="card mt-5" style="width: 18rem;">

      <div class="card-body">

        <h5 class="card-title"> <img src="./img/sun.png" width=100> <%= gossip.author %></h5>

        <p class="card-text"><%= gossip.content %></p>

        <a href="#" class="card-link">  <%= link_to 'Show', gossip, class:'btn btn-primary' %>
          <%= link_to 'Edit', edit_gossip_path(gossip), class:'btn btn-warning' %>
          <%= link_to 'Destroy', gossip, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></a>
      </div>
    </div>
  </div>
  <% end %>
</div>

GossipProject2/app/views/gossips/new.html.erb
<h1>New Gossip</h1>
<div class="container">
  <%= render 'form', gossip: @gossip %>

  <%= link_to 'Back', gossips_path %>
</div>

GossipProject2/app/views/gossips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @gossip.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @gossip.content %>
</p>

<%= link_to 'Edit', edit_gossip_path(@gossip) %> |
<%= link_to 'Back', gossips_path %>

GossipProject2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/">Home</a>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/contacts"> Nous contactez <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/gossips">Gossip</a>
      </li>
  </div>

</nav>

    <div class="container" style="padding-top: 5rem;">
      <%= yield %>
    </div>
  </body>
</html>

GossipProject2/app/views/pages/index.html.erb
<div class="container">
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </p>
</div>